# -*- coding: utf-8 -*-
"""SimpleMovieRecommendationsystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqFtnCszszp1BNWPdDVD4Zs9qhlnlccj
"""

import numpy as np

# ===============================
# Movie Recommendation System
# ===============================

# User ratings example
user1 = [5, 4, 0, 1]
user2 = [4, 5, 0, 1]
user3 = [1, 0, 5, 4]

users = [user2, user3]  # Other users to compare with user1

# Function to calculate similarity (cosine similarity)
def similarity(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    return dot_product / (norm_u * norm_v)  # Corrected norm_v

# Calculate similarity with all other users
similarities = []
for u in users:
    sim = similarity(user1, u)  # Call similarity for each user
    similarities.append(sim)

# Find the most similar user
best_match_index = np.argmax(similarities)

print("Best match user index:", best_match_index + 2)  # +2 because we are comparing user2 and user3

# Recommendation system
recommended_movies = [i for i, rating in enumerate(users[best_match_index]) if rating > 0 and user1[i] == 0] # we write user1[i]==0 because user1 wouldn't watch the same movie again.

print("Recommended movie indices:", recommended_movies)